# -*- coding: utf-8 -*-
"""Ron, screenshot to data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-A3mloCSFnfdnxBmDp3EsBv2sqDrx6p
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import matplotlib.pyplot as plt
import os
import random
from PIL import Image
import PIL.ImageOps 
import cv2
import numpy as np
import glob

from google.colab import files
uploaded_image = files.upload()
filename = next(iter(uploaded_image))

image = Image.open(filename)
inverted_image = PIL.ImageOps.invert(image)
inverted_image.save("score-inv.png")
im = Image.open("score-inv.png") 

width = im.size[0]
height = im.size[1]

left = width/4.15
top = height/4
right = width/1.32
bottom = height/1.45
  
im1 = im.crop((left, top, right, bottom))
im1.save("score-inv-cropped.png")
img = cv2.imread('score-inv-cropped.png')

df = pytesseract.image_to_data(img,lang='eng', output_type='data.frame')
df.to_csv('result.csv')

tempdir='/content/*'
files = glob.glob(tempdir)
try:
    for f in files:
      os.remove(f)
except Exception:
    pass
